# Generated by Django 5.1.2 on 2024-10-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_usersetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
